eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultzone: http://localhost:8761/
  instance:
    hostname: localhost

paymentservice: http://PaymentService/payment/paymentBook

